### ISSUE TITLE
Add route for getting the author info using an ObjectId

### ISSUE THREAD

**Issue by raymag** [raymag/floesia-api#11]

**Comment by alexandramj92** [comment]
I am interested in this issue!

**Comment by raymag** [comment]
Great, I'll assign it to you. Feel free to ask any questions if you are in doubt about something.

**Comment by alexandramj92** [comment]
> Great, I'll assign it to you. Feel free to ask any questions if you are in doubt about something.

do you want the route to be authenticated and do you want username, password, and email returned?

**Comment by raymag** [comment]
Oh yeah, I forgot to mention it. A public route in this case, so do not return the password.

**Comment by raymag** [comment]
Great job! I already merged it.
