### ISSUE TITLE
Create route for getting all poems of a given author

### ISSUE THREAD

**Issue by raymag** [raymag/floesia-api#18]
Basically a public route that only accepts GET methods, receives the ObjectId of an author as a URL parameter and returns all poems from that given author.

**Comment by thomaspimentel** [comment]
Hi @raymag, I just submitted a pull request for this issue. Let me know if there are any issues, and thank you for the opportunity!

**Comment by raymag** [comment]
Just merged it, thank you as well for the pull request!
