### ISSUE TITLE
Return author's info along with the token after login

### ISSUE THREAD

**Issue by raymag** [raymag/floesia-api#30]
Right now, every time you login with the route ```/login``` and are successful, you get something like this as return:
```json
{ "token": "as7d6a786as76d87as6fasd78as", "auth": true }
```
To make things easier in the fronted, I think it would be better if we were returned with the author's username, email and _id together with the token as well. Something like:
```json
{ 
"auth": true,
"token": "as7d6a786as76d87as6fasd78as",
"author": {
                "_id": "dsaj9sa0dasda09sd7as9d7a9sd8a0",
                "username": "Machado de Assis",
                "email": "k1d@bengla.com"
     }
 }
```

**Comment by sameerkavthekar** [comment]
Can you assign this to me please. Also how do I test the changes?
